# rustyssh
version: 1.0.{build}
image:
  - Visual Studio 2022
  - Visual Studio 2019
  - Ubuntu
  - macos
platform:
  - x64
configuration:
  - Release
clone_depth: 1
install:
  # install rust in windows
  - cmd: appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - cmd: rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain stable
  - cmd: set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - cmd: rustc -vV
  - cmd: cargo -vV
  # install yarn and rust in linux/mac
  - sh: npm install --global yarn
  - sh: curl https://sh.rustup.rs -sSf | sh -s -- -y
  - sh: source "$HOME/.cargo/env"
  - sh: cargo -vV
build_script:
  - yarn
  - yarn tauri build
test: off
