# rustyssh
version: 1.0.{build}
image:
  - Ubuntu
  - macos-catalina
  - Visual Studio 2019
platform:
  - x64
configuration:
  - Release
clone_depth: 1
environment:
  nodejs_version: "16"
for:
  - matrix:
      only:
        - image: Ubuntu
    cache:
      - $HOME/.cargo
    install:
      # install yarn and rust in linux/mac
      - npm install --global yarn
      - sudo apt-get install -y libsoup2.4-dev libjavascriptcoregtk-4.0-dev webkit2gtk-4.0-dev
      - curl https://sh.rustup.rs -sSf | sh -s -- -y
      - source "$HOME/.cargo/env"
      - cargo -vV
  - matrix:
      only:
        - image: Visual Studio 2019
    cache:
      - %USERPROFILE%\.cargo
    install:
      # install rust in windows
      - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
      - rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain stable
      - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
      - rustc -vV
      - cargo -vV
  - matrix:
      only:
        - image: macos-catalina
    cache:
      - $HOME/.cargo
    install:
      # install yarn and rust in linux/mac
      - npm install --global yarn
      - curl https://sh.rustup.rs -sSf | sh -s -- -y
      - source "$HOME/.cargo/env"
      - cargo -vV
build_script:
  - yarn
  - yarn tauri build
test: off
