# rustyssh
version: 1.0.{build}
image:
  - Visual Studio 2019
  - Ubuntu
  - macos
platform:
  - x64
configuration:
  - Release
clone_depth: 1
install:
  # install rust in windows
  - ps: appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - ps: rustup-init -yv --default-toolchain %channel% --default-host %target%
  - ps: set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - ps: rustc -vV
  - ps: cargo -vV
  # install yarn and rust in linux/mac
  - sh: npm install --global yarn
  - sh: curl https://sh.rustup.rs -sSf | sh -s -- -y
build_script:
  - yarn
  - yarn tauri build
test: off
